import { AxiosError } from "axios";
import { createOrderAction } from "./actions/create-order";

const botToken1 =
  "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJpSDJCdF8tNGdTS1ZLV1dELXVscVA4VmlJdUtVWU5FS2tuT01GeHBtTzA4In0.eyJleHAiOjE2MzEwMDIzNDIsImlhdCI6MTYzMDk5ODc0MiwianRpIjoiZTBlZTI0YzItZWMzNS00NmNmLTlkNTgtNzFmYTNhN2M5ZDE2IiwiaXNzIjoiaHR0cHM6Ly9hcGkub3BleC5kZXYvYXV0aC9yZWFsbXMvb3BleCIsInN1YiI6IjA5YTU2ZDhiLWYzNjQtNGM4OC04ZjhkLTNiMGE1MmU3MjA4MCIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiI2ZDQwZmFmZC04ZWU3LTRhYmMtYThhNi05M2MyNDdhOTEwMTkiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwic2NvcGUiOiJ0cnVzdCBwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiLaqdin2LHYqNixINuM2qnZhSDZhtmF2KfbjNi024wiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJkZW1vMSIsImdpdmVuX25hbWUiOiLaqdin2LHYqNixINuM2qnZhSIsImZhbWlseV9uYW1lIjoi2YbZhdin24zYtNuMIiwiZW1haWwiOiJkZW1vMUBvcGV4LmRldiJ9.hpHzQVAIMeO4i03kfR58p6kacMOJz-yj-itCSw_HUtlP5JQbdsVgD_MgAb-1CRASQPvKYCxMpk5NXBzyU2amWwEnl5zrqSfI3mX_45A_OwbHAICmK1ZKEhRmV1_ycnPqGSB1zNMGhTNZBENQeBO6WYYLSqEAkPv3j2T2KM5paPrNUVP9oVpRb1FTjVQklelU54BrUQFZwBHqHMxw7EsdTNntRFwRSiUM5W0f1xwBGuLHCuEbMUx5Py34WiFygQV-s2RbW8aRnPM5LRFpfcUZYxfSm_AZYQgWZG6WMzZWQoWjooDne-3tTh39Uuy8CzxEK4qlbQTAAm5JFh4gwoOp9Q";

const botToken2 =
  "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJpSDJCdF8tNGdTS1ZLV1dELXVscVA4VmlJdUtVWU5FS2tuT01GeHBtTzA4In0.eyJleHAiOjE2MzEwMDMyNTYsImlhdCI6MTYzMDk5OTY1NiwianRpIjoiZjNjMWIwNGQtM2YwYS00YmJhLWIzMjgtZjg0MWNkOGUxNDUzIiwiaXNzIjoiaHR0cHM6Ly9hcGkub3BleC5kZXYvYXV0aC9yZWFsbXMvb3BleCIsInN1YiI6IjU4ZWYyN2U4LTNhNzMtNGU3OC04MGQxLTJkOTc1ZDJhZmRlMyIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiJjMGIwZGY0ZS1iYTE5LTRlZTYtYWVhMy03OWQyYWFkOTFiMTUiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwic2NvcGUiOiJ0cnVzdCBwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiLaqdin2LHYqNixINiv2YjZhSDZhtmF2KfbjNi024wiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJkZW1vMiIsImdpdmVuX25hbWUiOiLaqdin2LHYqNixINiv2YjZhSIsImZhbWlseV9uYW1lIjoi2YbZhdin24zYtNuMIiwiZW1haWwiOiJkZW1vMkBvcGV4LmRldiJ9.Ty1SeVZo4KK81GicqHZQanMjnOlnzfcSMLdidYGuAWFGhWz-JuXCto_bnaOl-qeju_vTiprT-EY0AMVFkwtBWKLG3Oh8KjGWpIv01qwkQkZanVNqknmC3HHwg3GwMH-38yK8KpWgRyrxTxrbJLAJyHioVoGepiDboZCtW9vxKcTEPL048ACQyl7nxB2WTuXRk0OdChzhsyzILEBCl6fh8W7vfsFAzKJiDwgd9_XSLJOga5kRN-xvS2XW5WXlYJzlAkEODg6fCZJw7kxruckdHeGLvoXD03p7vt7uvJe6SaLI6uqzT8kQhcA4iql4GftHFi2RgUIoY3Nn5MVoQkrRrw";

const execute = async () => {
  try {
    await Promise.all([
      createOrderAction("BTCUSDT", 0.000001, 0.1, botToken1),
      // createOrderAction("ETHUSDT", botToken1),
    ]);
    await Promise.all([
      createOrderAction("BTCUSDT", 0.000001, 0.1, botToken2),
      // createOrderAction("ETHUSDT", botToken2),
    ]);
    console.log(`Executeed at ${new Date()}`);
    setTimeout(execute, 10000);
  } catch (error: any) {
    console.error(error.response?.data ?? error.message);
  }
};

execute();
