import { createOrderAction } from "./actions/create-order";

const optimus_prime =
  "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJpSDJCdF8tNGdTS1ZLV1dELXVscVA4VmlJdUtVWU5FS2tuT01GeHBtTzA4In0.eyJleHAiOjE2MzA5OTkxNjEsImlhdCI6MTYzMDk5NTU2MSwianRpIjoiYWY1ZjdkMjctZTljOS00ZTg1LWE3ZGMtNGViZmU4NDYzMzdlIiwiaXNzIjoiaHR0cHM6Ly9hcGkub3BleC5kZXYvYXV0aC9yZWFsbXMvb3BleCIsInN1YiI6IjFmYmUyMGI4LWExNzUtNDE5OS05Yzc1LWQzY2RhMTAyNzkwZCIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiI0YzM0ZTJlNC04YjA2LTRkYjQtODllOC0wYTNkNTMwZDQxMDkiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwic2NvcGUiOiJ0cnVzdCBwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJPcHRpbXVzIFByaW1lIiwicHJlZmVycmVkX3VzZXJuYW1lIjoib3B0aW11c19wcmltZSIsImdpdmVuX25hbWUiOiJPcHRpbXVzIiwiZmFtaWx5X25hbWUiOiJQcmltZSIsImVtYWlsIjoibWV0YWxpY24yMEBnbWFpbC5jb20ifQ.QQsoAM5ws8iF4o4v40orefJ1FqEzwW2OiFck_dQmB-Pd3Pj_lR8yV8qWscs-YHImZKKncQerKFKv3Ar_deXj2WD-wlIfRp2moNBPrruJcckZfzVstlVRVQkUikF-GwXKrSB2jWpBu83Nm4KiWkX2Ezkx5a1AbsjTYLlHl-8hbM_fQy6DXGi99VqoA0LbiABGmE4WIPqIsSV3MXnKirFqtsE9fU-p1Y2krGs8apA-VqXRGVRoOtBiyEJ9htCax8QGQVSpkcNKU7axnqEE1t_ntINZzPquVeZ8zBE0Af1veFPMjbAgw8PQ0fP5OQiWeW0VAlVH-gIiukrneTDfNpjHtQ";
const wall_e =
  "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJpSDJCdF8tNGdTS1ZLV1dELXVscVA4VmlJdUtVWU5FS2tuT01GeHBtTzA4In0.eyJleHAiOjE2MzA5OTkwNzksImlhdCI6MTYzMDk5NTQ3OSwianRpIjoiODJjZTk4YmUtZDNkOC00MjM1LWJlNTMtNzllYjU5OGNlZTVjIiwiaXNzIjoiaHR0cHM6Ly9hcGkub3BleC5kZXYvYXV0aC9yZWFsbXMvb3BleCIsInN1YiI6ImIzZmIxNzJjLWQzZmItNGMwZS1iOGRjLTEwZjNmNzExYTc4NSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiJlYzA1ZDE3Ni00MDIwLTRmYzktODc2ZS05OGFlM2NkOGY0ZGMiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwic2NvcGUiOiJ0cnVzdCBwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiV2FsbCBFIiwicHJlZmVycmVkX3VzZXJuYW1lIjoid2FsbF9lIiwiZ2l2ZW5fbmFtZSI6IldhbGwiLCJmYW1pbHlfbmFtZSI6IkUiLCJlbWFpbCI6Im1ldGFsaWNuMjFAZ21haWwuY29tIn0.REvgVFQDLKrB3yH6nLOxKtqrst6qZ8pnv9X7tfKuG84VlAeac-GA1kWNj71Zw_d612czO0e0Lv4-Tr-p52Jmp2aTMDrfNnavDb9GlhsmaPgS3Lgw9nTFbA3E9nbFDLKHdy1vSTnZaGCUqnRRteNHcXUQD4pIfb2WhCn1TbVFV_mEitGhyNWOvIYgLFyYnKYvIsRMorh_GTF8-8HZwgwid2N1SG-yJwfgji4pKnZmfvhWfpvyrvGuZDUqjFflniGR8F3MMMSXgB_cDrvYexSh999p4QO-BQ16f46zoKFTAp6Jbe4Q9qpJ5MsNiJKVH8XEYJxOn_FBPnuXPfCyf9tM3Q";

const execute = async () => {
  await Promise.allSettled([
    createOrderAction("BTCUSDT", optimus_prime),
    createOrderAction("ETHUSDT", optimus_prime),
  ]);
  await Promise.allSettled([
    createOrderAction("BTCUSDT", wall_e),
    createOrderAction("ETHUSDT", wall_e),
  ]);
  console.log(`Executeed at ${new Date()}`);
  setTimeout(execute, 5000);
};

execute();
